spring:
  application:
    name: courier_server
  messages:
    encoding: UTF-8
  profiles:
    active: ${PROFILE:local}

  servlet:
    multipart:
      max-file-size: 10MB         # 개별 파일 최대 크기
      max-request-size: 50MB      # 전체 요청 최대 크기
      file-size-threshold: 2KB    # 메모리에 저장할 임계값

